allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true

enablePrePostScripts: true
strictPeerDependencies: false

packages:
  - packages/examples/*
