allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true

enablePrePostScripts: true
minimumReleaseAge: 1440
strictPeerDependencies: false

packages:
  - packages/examples/*
